name: Build binary release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_windows64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Get dependencies
      run: |
        py -3.11 -m pip install -r requirements.txt
        py -3.11 -m pip install nuitka requests
        py -3.11 .github/workflows/get_upx.py -nf win64 .

    - name: Build binary
      run: |
        # For easily debuggable builds
        py ./.github/workflows/inject_buildstr.py app.py
        py ./.github/workflows/inject_buildstr.py BEAMinjector.py

        py -3.11 -m nuitka --onefile BEAMinjector.py
        mv dist/BEAMinjector.exe BEAMinject.exe
        py -3.11 -m nuitka --onefile app.py
        mv dist/app.exe BEAMinject_GUI.exe

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: BEAMinject_nightly
        path: |
          D:\a\BEAMinject\BEAMinject\BEAMinject.exe
          D:\a\BEAMinject\BEAMinject\BEAMinject_GUI.exe
